"""Match generated pytest modules against the imported endpoints.

A specification lists what an API offers; ``generated_tests/`` shows what is
already exercised. This module answers the only question that matters between
the two: which endpoints have no test yet.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from restpilot.generators.pytest_generator import test_name_for
from restpilot.models import OpenAPIDocument, OpenAPIEndpoint

#: Docstring line written into every generated module, used as the strongest match.
MARKER_TEMPLATE = "Generated by RestPilot for {method} {path}."

#: Only files pytest would collect are scanned.
TEST_FILE_PATTERN = "test_*.py"


@dataclass(frozen=True)
class EndpointCoverage:
    """Whether a single endpoint is exercised by a test module."""

    endpoint: OpenAPIEndpoint
    test_file: Path | None

    @property
    def is_covered(self) -> bool:
        """Whether a matching test module was found."""
        return self.test_file is not None


@dataclass(frozen=True)
class CoverageReport:
    """The result of comparing a document with a directory of tests."""

    directory: Path
    entries: list[EndpointCoverage]

    @property
    def covered(self) -> list[EndpointCoverage]:
        """Endpoints that already have a test."""
        return [entry for entry in self.entries if entry.is_covered]

    @property
    def missing(self) -> list[EndpointCoverage]:
        """Endpoints without a test."""
        return [entry for entry in self.entries if not entry.is_covered]

    @property
    def percentage(self) -> float:
        """Share of covered endpoints, or 100.0 when there is nothing to cover."""
        if not self.entries:
            return 100.0
        return len(self.covered) / len(self.entries) * 100


def collect_test_sources(directory: Path) -> dict[Path, str]:
    """Read every ``test_*.py`` file under ``directory``, recursively."""
    if not directory.is_dir():
        return {}
    return {
        path: path.read_text(encoding="utf-8", errors="replace")
        for path in sorted(directory.rglob(TEST_FILE_PATTERN))
        if path.is_file()
    }


def marker_for(endpoint: OpenAPIEndpoint) -> str:
    """Return the docstring marker RestPilot writes for an endpoint."""
    return MARKER_TEMPLATE.format(method=endpoint.method.value, path=endpoint.path)


def find_test_file(endpoint: OpenAPIEndpoint, sources: dict[Path, str]) -> Path | None:
    """Locate the module covering ``endpoint``.

    The generated marker wins, so a renamed or edited file is still recognized.
    Otherwise a test function named the way RestPilot would name it counts too,
    which lets hand-written tests be picked up.
    """
    marker = marker_for(endpoint)
    for path, text in sources.items():
        if marker in text:
            return path
    definition = re.compile(rf"^\s*def {re.escape(test_name_for(endpoint))}\s*\(", re.MULTILINE)
    for path, text in sources.items():
        if definition.search(text):
            return path
    return None


def build_report(
    document: OpenAPIDocument, directory: Path, endpoints: list[OpenAPIEndpoint] | None = None
) -> CoverageReport:
    """Compare the endpoints of ``document`` with the tests in ``directory``.

    Args:
        document: The imported specification.
        directory: Where generated tests live.
        endpoints: Restrict the report to these endpoints. Defaults to all of them.

    Returns:
        The coverage report, in document order.
    """
    sources = collect_test_sources(directory)
    selected = document.endpoints if endpoints is None else endpoints
    return CoverageReport(
        directory=directory,
        entries=[
            EndpointCoverage(endpoint=endpoint, test_file=find_test_file(endpoint, sources))
            for endpoint in selected
        ],
    )
