"""Generated by RestPilot for GET /api/v1/users/{user_id}.

Adjust the request data and assertions to match your scenario. RestPilot never
overwrites this file unless --force is passed.
"""

import httpx
import pytest


@pytest.mark.api
@pytest.mark.smoke
def test_get_user(api_client: httpx.Client) -> None:
    """Get user."""
    response = api_client.get("/api/v1/users/1")

    assert response.status_code == 200

    body = response.json()
    assert isinstance(body, dict)
