"""Matching generated tests against imported endpoints."""

from __future__ import annotations

from pathlib import Path

import pytest

from restpilot.generators.coverage import (
    build_report,
    collect_test_sources,
    find_test_file,
    marker_for,
)
from restpilot.generators.pytest_generator import render_test, write_test
from restpilot.models import HttpMethod, OpenAPIDocument, OpenAPIEndpoint
from restpilot.openapi.parser import find_endpoint

pytestmark = pytest.mark.unit


def endpoint_of(document: OpenAPIDocument, method: HttpMethod, path: str) -> OpenAPIEndpoint:
    endpoint = find_endpoint(document, method, path)
    assert endpoint is not None
    return endpoint


def generate(document: OpenAPIDocument, directory: Path, *paths: tuple[HttpMethod, str]) -> None:
    for method, path in paths:
        write_test(render_test(endpoint_of(document, method, path)), directory)


def test_generated_tests_are_recognized(tmp_path, document):
    generate(document, tmp_path, (HttpMethod.GET, "/health"))
    report = build_report(document, tmp_path)

    covered = {entry.endpoint.key for entry in report.covered}
    assert covered == {"GET /health"}
    assert report.covered[0].test_file == tmp_path / "test_health_check.py"
    assert len(report.missing) == 4
    assert report.percentage == pytest.approx(20.0)


def test_a_renamed_file_is_still_recognized(tmp_path, document):
    generate(document, tmp_path, (HttpMethod.GET, "/health"))
    renamed = tmp_path / "test_renamed_by_hand.py"
    (tmp_path / "test_health_check.py").rename(renamed)

    report = build_report(document, tmp_path)
    assert report.covered[0].test_file == renamed


def test_a_hand_written_test_following_the_convention_counts(tmp_path, document):
    (tmp_path / "test_manual.py").write_text(
        "def test_get_user(api_client):\n    assert True\n", encoding="utf-8"
    )
    report = build_report(document, tmp_path)
    assert {entry.endpoint.key for entry in report.covered} == {"GET /api/v1/users/{user_id}"}


def test_nested_directories_are_scanned(tmp_path, document):
    nested = tmp_path / "users"
    nested.mkdir()
    generate(document, nested, (HttpMethod.POST, "/api/v1/users"))
    report = build_report(document, tmp_path)
    assert report.covered[0].test_file == nested / "test_create_user.py"


def test_files_pytest_would_not_collect_are_ignored(tmp_path, document):
    endpoint = endpoint_of(document, HttpMethod.GET, "/health")
    (tmp_path / "helpers.py").write_text(marker_for(endpoint), encoding="utf-8")
    assert build_report(document, tmp_path).covered == []


def test_a_missing_directory_yields_no_coverage(tmp_path, document):
    report = build_report(document, tmp_path / "absent")
    assert collect_test_sources(tmp_path / "absent") == {}
    assert report.percentage == 0.0
    assert len(report.missing) == 5


def test_an_empty_document_is_fully_covered(tmp_path):
    report = build_report(OpenAPIDocument(title="Empty", version="1.0.0"), tmp_path)
    assert report.entries == []
    assert report.percentage == 100.0


def test_the_report_can_be_restricted_to_a_selection(tmp_path, document):
    generate(document, tmp_path, (HttpMethod.GET, "/health"))
    selection = [endpoint_of(document, HttpMethod.GET, "/health")]
    report = build_report(document, tmp_path, selection)
    assert len(report.entries) == 1
    assert report.percentage == 100.0


def test_find_test_file_returns_none_without_sources(document):
    endpoint = endpoint_of(document, HttpMethod.GET, "/health")
    assert find_test_file(endpoint, {}) is None


def test_marker_identifies_the_endpoint(document):
    endpoint = endpoint_of(document, HttpMethod.DELETE, "/api/v1/users/{user_id}")
    assert marker_for(endpoint) == "Generated by RestPilot for DELETE /api/v1/users/{user_id}."
    assert marker_for(endpoint) in render_test(endpoint).content
